---
Name: app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'default'
    - '$default'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - app/css/cms.css
  help_link: 'http://silverstripe.bigfork.co.uk/v3/'
SilverStripe\Control\Email\Email:
  admin_email: ''
SilverStripe\Core\Injector\Injector:
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\SiteConfigExtension
