---
Name: app
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'default'
    - '$default'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - app/css/cms.css
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'themes/default/dist/css/editor.css'
SilverStripe\Control\Email\Email:
  admin_email: ''
SilverStripe\Core\Injector\Injector:
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - App\Extensions\Assets\DBFileExtension
SilverStripe\ORM\FieldType\DBString:
  extensions:
    - App\Extensions\ORM\DBStringExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\SiteConfig\SiteConfigExtension
SilverStripe\CMS\Model\RedirectorPage:
  extensions:
    - App\Extensions\CMS\RedirectorPageExtension
SilverStripe\CMS\Model\SiteTree:
  create_default_pages: false
---
After: '#blogconfig'
Only:
  moduleexists: 'silverstripe/blog'
---
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - App\Extensions\Blog\BlogPostExtension
SilverStripe\Security\Member:
  extensions:
    - App\Extensions\Blog\BlogMemberExtension
