.live: &live
  hostname: '__HOSTNAME__'
  user: '__USER__'
  api_key: ''
  zone_id: ''

.staging: &staging
  hostname: '__HOSTNAME__'
  user: '__USER__'

.defaults: &defaults
  repository: '__REPOSITORY__'
  deploy_path: '~/public_html'
  roles:
    - 'app'

production:
  <<: *live
  <<: *defaults
  stage: production
prod:
  <<: *live
  <<: *defaults
  stage: production
live:
  <<: *live
  <<: *defaults
  stage: production

staging:
  <<: *staging
  <<: *defaults
  stage: staging
stage:
  <<: *staging
  <<: *defaults
  stage: staging
test:
  <<: *staging
  <<: *defaults
  stage: staging
