#!/bin/bash

## Description: Run yarn inside the default theme directory
## Usage: theme [flags] [args]
## Example: "ddev theme install" or "ddev theme watch" or "ddev theme build"
## ExecRaw: true
## HostWorkingDir: true

if [ $1 = "watch" ]; then
    yarn --cwd themes/default run dev
elif [ $1 = "prod" ]; then
    yarn --cwd themes/default run build
elif [ $1 = "build" ]; then
    yarn --cwd themes/default run build
else
    yarn --cwd themes/default "$@"
fi

